# Generated by Django 4.0.4 on 2022-04-26 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_tblcamsecret'),
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblalert',
            name='camera',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='camera.tblcamera'),
            preserve_default=False,
        ),
    ]
