# Generated by Django 4.0.4 on 2022-04-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluserdetails',
            name='warnLocations',
            field=models.ManyToManyField(to='locations.tblmainlocations'),
        ),
    ]
