# Generated by Django 4.0.4 on 2022-04-17 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tbluserdetails_warnlocations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbluserdetails',
            name='email',
        ),
    ]
